# Generated by Django 3.1.1 on 2020-09-22 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=1000)),
                ('officeLocation', models.CharField(max_length=1000)),
                ('points', models.IntegerField()),
                ('lastInteraction', models.DateTimeField()),
            ],
            options={
                'ordering': ['points'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=1000)),
                ('officeLocation', models.CharField(max_length=1000)),
                ('teamSupervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.employee')),
            ],
            options={
                'ordering': ['teamSupervisor'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.team'),
        ),
    ]
