# Generated by Django 3.1.1 on 2020-09-25 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=100)),
                ('employeeTeam', models.CharField(max_length=100)),
                ('officeLocation', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('lastInteraction', models.DateTimeField()),
            ],
            options={
                'ordering': ['points'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=100)),
                ('officeLocation', models.CharField(max_length=100)),
                ('teamSupervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.employee')),
            ],
            options={
                'ordering': ['teamSupervisor'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=100)),
                ('officeLocation', models.CharField(max_length=100)),
                ('feedbackText', models.CharField(max_length=1000)),
                ('feedbackSentimentAnalysis', models.CharField(max_length=1000)),
                ('feedbackAspectBasedSA', models.CharField(max_length=1000)),
                ('feedbackRedFlags', models.CharField(blank=True, max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('teamSupervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.employee')),
            ],
        ),
    ]
