# Generated by Django 3.1.1 on 2020-09-25 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedbackAspectBasedSA',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackSentimentAnalysis',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbackText',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='teamSupervisor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='feedback.employee'),
        ),
    ]
