# Generated by Django 3.1.1 on 2020-09-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200925_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedbackText',
            field=models.CharField(max_length=1000),
        ),
    ]
