# Generated by Django 3.1.1 on 2020-09-25 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20200925_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='teamSupervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='feedback.employee'),
        ),
    ]
