# Generated by Django 3.1.1 on 2020-09-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20200925_0502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employeeId']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastInteraction',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
